### ISSUE TITLE
link error with pods

### ISSUE THREAD

**Issue by muzerly** [EricssonResearch/openwebrtc-ios-sdk#16]
Hello, I'm install openwebrtc sdk to my project use cocoapods, it's successful. But when I build and run, it's exist some link errors: 

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_OpenWebRTC", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_OpenWebRTCNativeHandler", referenced from:
      objc-class-ref in WebRTCViewController.o
  "_OBJC_CLASS_$_OpenWebRTCSettings", referenced from:
      objc-class-ref in WebRTCViewController.o
ld: symbol(s) not found for architecture i386

here is my podfile:

\#Uncomment this line to define a global platform for your project
\#platform :ios, '6.0'

target 'XYUniCom' do
pod 'OpenWebRTC-SDK', :path => '../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
end

target 'XYUniCom-no-gpl-thirdparties' do
end

target 'LinphoneTester' do
end

**Comment by stefanalund** [comment]
Looks like you are running with the Simulator as the target. Does this error persist if you choose a Device instead?

**Comment by muzerly** [comment]
Hi, Thanks for reply.
I have tested on device, still have link errors:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_OpenWebRTCSettings", referenced from:
      objc-class-ref in WebRTCViewController.o
  "_OBJC_CLASS_$_OpenWebRTCNativeHandler", referenced from:
      objc-class-ref in WebRTCViewController.o
  "_OBJC_CLASS_$_OpenWebRTC", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7

**Comment by muzerly** [comment]
I use mac osx 10.9.5 and xcode 6.2

**Comment by superdump** [comment]
That looks like you maybe don't have the OpenWebRTC nor OpenWebRTC-SDK pods. Are you sure they were successfully installed?

**Comment by muzerly** [comment]
yes, it was generated Pods files and myproject.xcworkspace file, here is install log:

macbook:XYUniCom zhaoyan$ pod install
Analyzing dependencies

CocoaPods 0.37.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Fetching podspec for `OpenWebRTC-SDK` from `../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
Downloading dependencies
Using OpenWebRTC (0.1.4)
Using OpenWebRTC-SDK (0.1.1)
Generating Pods project
Integrating client project

[!] The `XYUniCom [Debug]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Release]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Distribution]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distribution.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Distribution]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distribution.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Distribution]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distribution.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [Distribution]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distribution.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [DistributionAdhoc]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distributionadhoc.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [DistributionAdhoc]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distributionadhoc.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [DistributionAdhoc]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distributionadhoc.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYUniCom [DistributionAdhoc]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-XYUniCom/Pods-XYUniCom.distributionadhoc.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by stefanalund** [comment]
The warnings you get with `$(inherited)` needs to be taken seriously. I remember having this issue in the NativeDemo: https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/NativeDemo

Check if this is set by comparing with NativeDemo:

![screen shot 2015-04-22 at 09 09 48](https://cloud.githubusercontent.com/assets/190856/7269003/66ce37a4-e8cf-11e4-82b8-f61e6327c979.png)

**Comment by muzerly** [comment]
here is my settings:

![0a6c0f12-f605-41f0-a666-84ff8f183cff](https://cloud.githubusercontent.com/assets/778128/7269765/40be1c66-e909-11e4-80f5-88ef4fe369dd.png)

**Comment by stefanalund** [comment]
I'm pretty sure this is related to the warnings you get from pod install. Did you solve the issue? If not, any way you can share your project file?

**Comment by muzerly** [comment]
Hi, Sorry I can't share my project, it's too large, I have changed to use another webrtc lib, it's works fine. I think this issue is relate to my system. not is the sdk problem, I will close this issue. Thanks
