### ISSUE TITLE
OpenWebRTC.podspec is pointing to not existing OpenWebRTC_0.3.0.zip

### ISSUE THREAD

**Issue by evermeer** [EricssonResearch/openwebrtc-ios-sdk#17]
The OpenWebRTC.podspec is pointing to the following file:
http://static.verkstad.net/OpenWebRTC_0.3.0.zip
That file does not exist.

**Comment by superdump** [comment]
Are you sure? If I click that link, the file downloads. We'll be moving that to GitHub soon.

**Comment by evermeer** [comment]
Strange, now it downloads...
Since I also could not see it when going to http://static.verkstad.net/ I assumed it wasn't there.

**Comment by evermeer** [comment]
But then again... I still get this error when doing a 'pod install' 

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /Users/evermeer/Desktop/MyApp/Pods/OpenWebRTC/file.zip http://static.verkstad.net/OpenWebRTC_0.3.0.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  7  129M    7 9812k    0     0  5237k      0  0:00:25  0:00:01  0:00:24 5235kcurl: (56) Recv failure: Connection reset by peer

A manual download of the file does work

**Comment by evermeer** [comment]
When mannually executing that curl command, the first 4 times failed, the 5th time it did work. Could it be a timing issue?

**Comment by superdump** [comment]
I can't get it to fail here...

**Comment by Rajputvikassingh** [comment]
HI,
I have get this error when doing a 'pod install'

Analyzing dependencies
Downloading dependencies
Installing OpenWebRTC (0.3.1)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/91/8stff88n3wd2cmhft1bg6kzr0000gn/T/d20150616-6091-1ilsh9/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (52) Empty reply from server

can any one help me about this issues..

**Comment by superdump** [comment]
This should be fixed shortly. Server troubles...

**Comment by Rugvip** [comment]
Should be up and running now

**Comment by Rajputvikassingh** [comment]
Thanks... currently working prefect.

**Comment by REKURDennis** [comment]
I'm facing the same issue.
Can anybody help me? Or should I just wait?


Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OpenWebRTC-SDK` from `https://github.com/EricssonResearch/openwebrtc-ios-sdk.git`
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.1)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/z1/73mhjd211bjd2b2l3pk4sfzc0000gn/T/d20150724-34557-15yg038/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1  129M    1 2234k    0     0  1992k      0  0:01:06  0:00:01  0:01:05 1993kcurl: (56) Recv failure: Connection reset by peer

**Comment by superdump** [comment]
Downloading seems to work for me.

**Comment by REKURDennis** [comment]
Thank you for your very fast reply.
If I tried to download the zip-File (by clicking on the link in chrome), the download starts and then fails after a few seconds with the message "Error - Network error".

Since you said it is working for you I tried to download the file with another IP by establishing a VPN connection to a server in the USA (I live in Germany). And it works!
If I turn it off, the download fails again. Maybe it is an issue with my local provider.

**Comment by tom7505** [comment]
Can anybody help me?
I have get this error when doing a 'pod install'

Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OpenWebRTC-SDK` from `https://github.com/EricssonResearch/openwebrtc-ios-sdk.git`
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.1)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/kt/jkj7xr25661_nnv2y_xgmdjc0000gn/T/d20150823-15826-1scw1es/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  129M    2 2876k    0     0  2481k      0  0:00:53  0:00:01  0:00:52 2480kcurl: (56) Recv failure: Connection reset by peer

A manual download of the file does not work.
 
Thx

**Comment by superdump** [comment]
A manual download of the file works for me.

**Comment by junealbertpw** [comment]
Can anyone succesfully fix this issue? I'm gettting this issue after running "pod install"

**Comment by stefanalund** [comment]
@junealbertpw can you run `pod install --verbose` and report back the logs?

**Comment by junealbertpw** [comment]
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:130:in `rescue in execute_command'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:128:in `execute_command'
/.rvm/gems/ruby-2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:152:in `block in executable'
/.rvm/gems/ruby-2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:86:in `download_file'
/.rvm/gems/ruby-2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:23:in `download!'
/.rvm/gems/ruby-2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:80:in `block in download'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:145:in `block in ui_action'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:144:in `ui_action'
/.rvm/gems/ruby-2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:78:in `download'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:110:in `download_source'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:65:in `download_request'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:170:in `download'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:153:in `block in uncached_pod'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `call'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:34:in `download'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:113:in `download_source'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:339:in `install_source_of_pod'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:306:in `block (2 levels) in install_pod_sources'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:305:in `block in install_pod_sources'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `each'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `install_pod_sources'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:146:in `block in download_dependencies'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:144:in `download_dependencies'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:106:in `install!'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by stefanalund** [comment]
Hmm, nothing much useful there. Try running `rm -rf Pods/ Podfile.lock` and then re-run `pod install`.

**Comment by junealbertpw** [comment]
Hi Stefanalund, same issue happen after running pod install

**Comment by stefanalund** [comment]
I can't see anything in the logs that points to the OpenWebRTC pod specifically. Can you install other pods?

**Comment by junealbertpw** [comment]
Yes I can install other pods except this WebRTC-SDK

**Comment by zhujie0** [comment]
failed to connect to static.verkstad.net port 80: connection refused

**Comment by junealbertpw** [comment]
I also did tried the NativeDemo and the video from other participants is not showing

**Comment by stefanalund** [comment]
@junealbertpw please report that as a separate Issue. Thanks.

**Comment by junealbertpw** [comment]
I will, Thanks

**Comment by royherma** [comment]
still happenning..has this not been fixed?

**Comment by stefanalund** [comment]
@royherma please use the latest version 0.3.93.

**Comment by royherma** [comment]
@stefanalund same thing, super wierd...download stops both when using pods:

2  158M    2 3717k    0     0  1708k      0  0:01:34  0:00:02  0:01:32 1708kcurl: (56) **Recv failure: Connection reset by peer**

Probably will need to try from a different connection to see if this problem is specific to my connection...

**Comment by stefanalund** [comment]
@royherma any luck?

**Comment by hboughzala** [comment]
Hello,

I made multiple tries and had success getting the file to run native demo or bowser, also tried different file versions to check and all failed.

Here is the log of "pod install --verbose"
 
-> Installing OpenWebRTC (0.3.1)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/pm/mqwmkz8d5ml7wbs_wnsdnvch0000gn/T/d20160211-26536-1osl9iy/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip
   --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Operation timed out

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/pm/mqwmkz8d5ml7wbs_wnsdnvch0000gn/T/d20160211-26536-1osl9iy/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Operation timed out

**Comment by haichuand** [comment]
I'm having the same problem:
[!] /usr/bin/curl -f -L -o /var/folders/rf/8qvf4hlx3qxbgcwnfjdgdx6c0000gn/T/d20160217-5857-17rqt5u/file.zip http://static.verkstad.net/OpenWebRTC_0.3.94.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Operation timed out

Server down? Is there an alternative?

**Comment by stefanalund** [comment]
We hope to have a server back up in a day or two. Sorry for the delay.

**Comment by stefanalund** [comment]
@haichuand a new version 0.3.95 is now available from a new server, please try running `pod install` again.

**Comment by liwuking** [comment]
@stefanalund   version 0.3.95 can't pull download

**Comment by stefanalund** [comment]
I can access it https://pods.cct.ericsson.net

**Comment by JCloudYu** [comment]
Hello! I'm trying to build your NativeDemo, but I end up with "pods.cct.ericsson.net not found" error
