### ISSUE TITLE
Error when using podfile with use_frameworks!

### ISSUE THREAD

**Issue by evermeer** [EricssonResearch/openwebrtc-ios-sdk#18]
Since my project uses multiple libraries written in Swift, I need to add use_frameworks! to my pod file. When doing that, you will get an error when using:
```
pod 'OpenWebRTC-SDK',  :git => ' https://github.com/EricssonResearch/openwebrtc-ios-sdk.git'
```
The error that you will get is something like:
```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/evermeer/Desktop/MyApp/Pods/OpenWebRTC/OpenWebRTC.framework)
```
For now I do have a workaround, but that means that I need to do some manual changes after each 'pod install'. The workaround is:
- Clone the openwebrtc-ios-sdk.git next to your folders project
- Download OpenWebRtc.framework and put that in the root folder.
- Put the following line in your pod file (instead of the one above, make sure the path is ok)
    pod 'OpenWebRTC-SDK', :path => '../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
- Edit that .podspec and remove the reference to OpenWebRTC
- manually include OpenWebRTC into your project and add header search path to the included header folder

After this you can do a 'pod install' and you will get the latest version of the OpenWebRTC-SDK. You have to manually download new versions of the OpenWebRTC.framework. After doing a 'pod install' you have to fix the build manually by adding the OpenWebRTC.framework to the OpenWebRTC-SDK and fix it's header search paths.

I was wondering if there is a better workaround for this problem? Would it help moving the OpenWebRtc.framework to the Xcode framework folder (where, how) and let all reference that?

**Comment by evermeer** [comment]
Here is the OpenWebRTC-SDK.podspec that I now use:
```
Pod::Spec.new do |s|
  s.name         = "OpenWebRTC-SDK"
  s.version      = "0.1.1"
  s.summary      = "SDK for adding WebRTC to your app through OpenWebRTC"
  s.homepage     = "http://www.openwebrtc.io"
  s.license      = { :type => "BSD-2", :file => "LICENSE" }
  s.author       = { "Ericsson AB" => "labs@ericsson.com" }
  s.social_media_url = "https://twitter.com/OpenWebRTC"
  s.platform     = :ios, "7.0"
  s.source       = {
    :git => "https://github.com/EricssonResearch/openwebrtc-ios-sdk.git",
    :tag => "0.1.1"
  }
  s.source_files = "SDK/*.{h,m}"
  s.resources = "Resources/**"
  #s.resource = { :http => "https://github.com/EricssonResearch/openwebrtc/blob/master/bridge/client/sdp.js" }
  s.frameworks = "JavaScriptCore", "VideoToolbox", "AssetsLibrary", "CoreVideo", "CoreAudio", "CoreGraphics", "OpenGLES"
  s.libraries = "c++", "resolv", "iconv"
  s.requires_arc = true
end
```
So after using that I 'only' have to manually add the OpenWebRTC.framework to the OpenWebRTC-SDK and add the header search path.

**Comment by evermeer** [comment]
My workaround does not seem to work. When I add this import to a swift file:
```
import OpenWebRTC_SDK
```
Then I will get the following error:
```
/Users/evermeer/Desktop/MyApp/openwebrtc-ios-sdk/SDK/OpenWebRTC.h:36:9: Include of non-modular header inside framework module 'OpenWebRTC_SDK.OpenWebRTC'
```
Which is on the line:
```
#import "owr.h"
```

**Comment by evermeer** [comment]
hmm... I tried to put in the correct import to owr.h but apperently that is not needed. When I comment out that import line my app compiles again.

**Comment by stefanalund** [comment]
@evermeer But then it's not possible to use OpenWebRTC, correct? I wonder if this is related to framework module maps: http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by evermeer** [comment]
I think it's related to : https://github.com/CocoaPods/CocoaPods/issues/3194
I'm not sure what the correct way is to solve this.
The use_frameworks! is required if you are using Swift

For now the workaround I described above works good enough for me.
It just means that after every 'pod update' I need to do some manual fixes.

**Comment by evermeer** [comment]
When using frameworks there is an other problem. the file sdp.js will not be found in the main bundle because it's part of a framework. So this line will fail:

            NSString *path = [[NSBundle mainBundle] pathForResource:@"sdp" ofType:@"js"];

Instead you should use:

            NSString *path = [[NSBundle bundleForClass:[self class]] pathForResource:@"sdp" ofType:@"js"];

**Comment by stefanalund** [comment]
Right. Would you mind submitting a PR? Thanks.

**Comment by evermeer** [comment]
OK, I created a PR

**Comment by evermeer** [comment]
update: 
When copying the OpenWebRTC.framework to the folder: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library 
And then including the framework in the .podspec by using:
  s.frameworks = "JavaScriptCore", "VideoToolbox", "AssetsLibrary", "CoreVideo", "CoreAudio", "CoreGraphics", "OpenGLES", "OpenWebRTC"
Will bring you one step further. Then it will be included. The only thing that you then need to add is the 'header search path' to the OpenWebRTC.framework/headers folder (recursive)
Maybe there is a solution to add that as well?

**Comment by stefanalund** [comment]
I think a Module Map is what's missing. Created a new Issue to track this https://github.com/EricssonResearch/openwebrtc/issues/379.

**Comment by stefanalund** [comment]
This was fixed by @evermeer. Thanks!
