### ISSUE TITLE
Support ICE trickle

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc-ios-sdk#2]
Send ICE candidates as they become available rather than only when generating the answer.

**Comment by stefanalund** [comment]
@Rugvip could you have a look at this one?

**Comment by stefanalund** [comment]
Fixed in https://github.com/EricssonResearch/openwebrtc-ios-sdk/pull/45.

**Comment by xelven** [comment]
ref: https://github.com/EricssonResearch/openwebrtc-ios-sdk/issues/67
