### ISSUE TITLE
Support for one broadcast and multiple viewers.

### ISSUE THREAD

**Issue by evermeer** [EricssonResearch/openwebrtc-ios-sdk#22]
I think WebRTC should be able to support one broadcaster with multiple viewers Like apps like Periscope and Meerkat are doing. With this SDK it looks like you can only join a room and initiate a one to one communication. I would like to have the possibility to just follow / watch a stream from a room. 

Is there a workaround with the current library to achieve this?
Is such functionality planned on the roadmap for this SDK? 
If I would want to implement this functionality in the SDK myself, how much would I need to change? Do you have any pointers about what to change where?

**Comment by superdump** [comment]
OpenWebRTC can be used to send to multiple clients or to only receive, but you would need to implement the appropriate signalling and application for that.

A lot of work has been done on the Android SDK and I think a good plan going forwards would be to synchronise the iOS API with the Android API for the sake of consistency. The Android SDK supports send only and receive only.

Some work would probably also be needed on the core of OpenWebRTC to figure out the most effective way to stream to multiple clients without encoding once for each client and while retaining the modularity and clean API.

**Comment by ShGup** [comment]
Hi,
Is this something coming with the SDK. Right now, the ios sdk feels like in a very early state of development with very limited functionality for one to one calls.

**Comment by xelven** [comment]
Hi, I have same require for the multiple N to N video chat,
is there any way can let me add more remote-view or I need to create OpenWebRTCNativeHandler one by one?

**Comment by superdump** [comment]
One by one I expect. Each is for one client.

**Comment by stefanalund** [comment]
To be honest there may be some things that needs fixing in the API in order to support multiple `OpenWebRTCNativeHandler`s. There are a few singleton:ish things that you may have to deal with, but nothing impossible I should think.
