### ISSUE TITLE
When doing OwrVideoPayload rotation changes during a call, video goes black on the other OWR iOS client

### ISSUE THREAD

**Issue by manuroe** [EricssonResearch/openwebrtc-ios-sdk#23]
In the attempt to manage video orientation, I hack the SDK to send a new send_payload with the new rotation on device orientation change. I used OwrVideoPayload rotation as adviced by @superdump . The code is in our(matrix.org) fork/branch: https://github.com/matrix-org/openwebrtc-ios-sdk/tree/cvo_support.

OWR does not support CVO yet (https://github.com/EricssonResearch/openwebrtc/issues/396) but it currently rotates video before sending - which is one case described in the CVO spec.

Rotation during iOS OWR <-> Chrome/Firefox calls works nicely. I can see the video rotates on Chrome.
But it fails on iOS OWR <-> iOS OWR calls, the video becomes black on the other device.

It would be nice if the feature could work for full OWR calls.

To reproduce the issue:
 - use the develop branch of Matrix Console (it will point to the Matrix openwebrtc-ios-sdk fork)
 - install Matrix Console on 2 devices
 - make a video call between the 2
 - rotate one device
 -> The video becomes black on the other device

**Comment by stefanalund** [comment]
There is now proper support for video rotation in the SDK. Reopen if this does not solve this problem.
