### ISSUE TITLE
Issue with selfView orientation

### ISSUE THREAD

**Issue by manuroe** [EricssonResearch/openwebrtc-ios-sdk#24]
It is a pity that the self view is rotated (even in NativeDemo). I attempt to fix it in the matrix fork (https://github.com/matrix-org/openwebrtc-ios-sdk/tree/cvo_support) by setting the rotation property of the OwrVideoRenderer instance that manages the self video.
It works fine but only for the first call.

On next calls, setting the rotation property has no effect. I suspect that OWR keeps the firts instance of the "object" managing the camera. Then next created OwrVideoRenderer for next call are not directly linked to the camera.

This suspicion comes from this comment in OpenWebRTCNativeHandler.m:
`/* We ref the sources because we want them to stay around. On iOS they will never be
   unplugged, I expect, but it's safer this way. */`
src: https://github.com/EricssonResearch/openwebrtc-ios-sdk/blob/master/SDK/OpenWebRTCNativeHandler.m#L1033-L1035

(By the way, the corresponding OwrVideoRenderer is not released in the Reset method)

To reproduce the issue:
 - use the develop branch of Matrix Console (it will point to the Matrix openwebrtc-ios-sdk fork)
 - install Matrix Console on 1 device
 - Attempt to place a video call
 - Rotate the device: the self view follows the orientation and it is always rotated as expected
 - Cancel the call
 - Place a new call
 - Rotate the device -> this time, the self view does not follow the orientation

**Comment by stefanalund** [comment]
There is now a proper API for setting rotation from the SDK. Closing.
