### ISSUE TITLE
Installing OpenWebRTC do not go on

### ISSUE THREAD

**Issue by taojigu** [EricssonResearch/openwebrtc-ios-sdk#37]
I run "pod install" under NativeDemo, cocoapods version:0.38.2

The result is followed, it seems "Installing OpenWebRTC (0.3.1)" forever, no go on.

Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OpenWebRTC-SDK` from `https://github.com/EricssonResearch/openwebrtc-ios-sdk.git`
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.1)

**Comment by stefanalund** [comment]
Seems like you cannot download the OpenWebRTC.framework file included in OpenWebRTC pod. Are you by any chance behind a strict firewall?

Try running "pod install --verbose" to paste the extra info here.

**Comment by taojigu** [comment]
Install successfully.
But  it show "file not found" error in OpenWebRTC-SDK Project:
#import "owr.h"  in OpenWebRTC.h
#include <owr_bridge.h>  in  OpenWebRTCViewController.m

**Comment by stefanalund** [comment]
Try removing both /Pods folder and Podfile.lock before again running `pod install --verbose`.

**Comment by taojigu** [comment]
I delete /Pods and Podfile.lock , re-pod install . In NativeDemo
But "owr.h" is not found in "OpenWebRTC.h" and "OpenWebRTCNativeHandler.m"

**Comment by stefanalund** [comment]
I have seen this error when using newer CocoaPods than 0.38.2, but you said you were using 0.38.2, right?

**Comment by taojigu** [comment]
There are 3 version  of cocoapods on my Mac :0.36.0; 0.38.2; 0.39.0 ; I unstall the 0.39.0, defautl version is 0.38.2,  but The error still exist.

**Comment by stefanalund** [comment]
And you got no errors or warnings when running `pod install --verbose`?

**Comment by taojigu** [comment]
I have not seen any error or warning, The result is 

-> Installing OpenWebRTC-SDK (0.3)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `InAppSettingsKit` iOS 8.0
    - Installing target `OpenWebRTC-SDK` iOS 8.0
    - Installing target `Pods-NativeDemo` iOS 8.0
    - Installing target `Pods-NativeDemoTests` iOS 8.0
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-NativeDemo` (`NativeDemo.xcodeproj` project)

Integrating target `Pods-NativeDemoTests` (`NativeDemo.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from
    `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb`

Sending stats
      - InAppSettingsKit, 2.4.4
      - OpenWebRTC, 0.3.1
    - cocoapods-stats from
    `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb`

Sending stats
      - InAppSettingsKit, 2.4.4
      - OpenWebRTC, 0.3.1

**Comment by stefanalund** [comment]
And you are opening the `NativeDemo.xcworkspace` file?

**Comment by taojigu** [comment]
Yes, I open the workspace file

**Comment by stefanalund** [comment]
Really sorry but I cannot reproduce this. We recently landed updates to NativeDemo, could you please update to current master and try again? Thanks.

**Comment by taojigu** [comment]
I update the NativeDemo , it works now, Thank you

**Comment by stefanalund** [comment]
Great! No problem.
