### ISSUE TITLE
Failed to connect to static.verkstad.net port 80: Operation timed out

### ISSUE THREAD

**Issue by zhujie0** [EricssonResearch/openwebrtc-ios-sdk#43]
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.91)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/l9/1pqqwd2161x02qtzjr3hp_5c0000gn/T/d20151204-21529-1fm76zh/file.zip http://static.verkstad.net/OpenWebRTC_0.3.91.zip 

 --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Operation timed out

**Comment by stefanalund** [comment]
The server is down at the moment, we are working on it.

**Comment by stefanalund** [comment]
Server is back up now. Closing.
