### ISSUE TITLE
Some ld Warning in the project

### ISSUE THREAD

**Issue by onurvarrrr** [EricssonResearch/openwebrtc-ios-sdk#46]
Hi,
I just downloaded SDK using 

pod 'OpenWebRTC', '~> 0.1'
pod 'OpenWebRTC-SDK',  :git => 'https://github.com/EricssonResearch/openwebrtc-ios-sdk.git'

but I got these error

![image](https://cloud.githubusercontent.com/assets/4017312/11610759/81a34630-9bb4-11e5-9ffc-9288e430626c.png)

as far as I know these are related with libiconv.tdb which are missing in project. So I added libiconv.tdb using 'Link Binary With Libraries' and compiled successfully. But then I realized that I got some warnings in project. Please see attached screenshot.

![image](https://cloud.githubusercontent.com/assets/4017312/11610706/463d494c-9bb4-11e5-9d25-2097ddf3c405.png)

I know these warnings are related with running the app on simulator (~ i386) and i dont get these warnings on when compiling for real devices like armv7. But how can i remove these warnings ? or is there any approach to resolve these warnings. Or should i just ignore these warnings ?

Thanks

**Comment by stefanalund** [comment]
You are pointing to a rather old version of the OpenWebRTC pod (0.1). The latest is 0.3.91. Proper support for running in the simulator has now also been added.
