### ISSUE TITLE
Pod installation not working

### ISSUE THREAD

**Issue by royherma** [EricssonResearch/openwebrtc-ios-sdk#49]
Getting errors when using both "styles" of podfile setup:

For option 1 getting (from README.MD pod installation instructions)...
```
[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/8r/cljczzvx5c35dg_dgn1fw8nw0000gn/T/d20160104-30347-1wo9dyu/file.zip http://static.verkstad.net/OpenWebRTC_0.3.93.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  158M    2 3499k    0     0  1543k      0  0:01:45  0:00:02  0:01:43 1543kcurl: (56) Recv failure: Connection reset by peer
```

And for option 2 getting:
```
Fetching podspec for `OpenWebRTC-SDK` from `../../../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
[!] No podspec found for `OpenWebRTC-SDK` in `../../../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
```

Is this temporary or is the pod just down?

Thanks

**Comment by royherma** [comment]
Doing some more research, even if I try to DL the .zip through a browser, it fails after several seconds. I think it could have to do with the "Only secure origins are allowed" error. Anyway to fix?

**Comment by superdump** [comment]
Very odd that it stops for you after just a few seconds. I haven't had the same problem. @stefanalund - does it work for you?

**Comment by royherma** [comment]
@superdump I'm pretty positive it has something to do with "not having a secure connection", the same way its not letting me initiate a rtc on the demo @ http://demo.openwebrtc.org:38080/ . Wouldn't think it would be an issue on pods but it might be...

**Comment by wangchauyan** [comment]
I encountered this problem before, and then I download it manually instead of using pod install.

**Comment by stefanalund** [comment]
Is this still an issue? I can download it from a browser at least.

**Comment by appmakerpeng** [comment]
I have the same  problem. pod interrupt!

**Comment by stefanalund** [comment]
Can you guys download http://static.verkstad.net/OpenWebRTC_0.3.93.zip in for example the browser? It works for me (and also `pod install`).

**Comment by appmakerpeng** [comment]
ok，thanks! I will try it later.

**Comment by coralsaw** [comment]
@stefanalund 
Hi Stefan, I cannot manually access _03.93.zip (tried from 2 computers, 2 different browsers, 3 different networks). Also, the pod asks for http://static.verkstad.net/OpenWebRTC_0.3.91.zip which it doesn't find and bombs out. Could you please advise? Thanks.

**Comment by superdump** [comment]
This will be fixed today - we had a hardware failure.

**Comment by stefanalund** [comment]
A new version 0.3.95 is now available from a new server, please try running `pod install` again.

**Comment by DAOCUONG** [comment]
i Still got the error Installing OpenWebRTC (0.3.1)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/0z/dh1r82yn153__2y5sfp8_tgc0000gn/T/d20160220-26592-1x7gshz/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Connection refused

**Comment by stefanalund** [comment]
The pods are now available on a new server: https://pods.cct.ericsson.net/

If you update to use the latest pod (0.3.95) it points to the new server.

**Comment by simonfi** [comment]
Are there any more updates on this issue? I'm running into problems also trying to include the OpenWebRTC Cocoa Pod. It seems pods.cct.ericsson.net does not even resolve now:

```
$ nslookup pods.cct.ericsson.net - 8.8.8.8                                                                                                                                                                          
Server:     8.8.8.8
Address:    8.8.8.8#53

** server can't find pods.cct.ericsson.net: NXDOMAIN
```
