### ISSUE TITLE
static.verkstad.net port 80: Operation timed out

### ISSUE THREAD

**Issue by RomanBalmus** [EricssonResearch/openwebrtc-ios-sdk#56]
Analyzing dependencies
Pre-downloading: `OpenWebRTC-SDK` from `https://github.com/EricssonResearch/openwebrtc-ios-sdk.git`
Downloading dependencies
Installing InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.94)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/x9/jfqhyzjs50s8pry2bxgz0s6r0000gn/T/d20160211-27659-1dgqb0w/file.zip http://static.verkstad.net/OpenWebRTC_0.3.94.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Operation timed out

**Comment by stefanalund** [comment]
The server is down due to a HW failure, we are working on it. Sorry for the inconvenience.

**Comment by hboughzala** [comment]
Hi Stefan,

I am trying to compile the native demo and the needed version is 0.3.1. Is there an alternative to the server file that is currently down, or could you share it so that i put it somewhere else locally for the pod install.

Thanks

**Comment by stefanalund** [comment]
We hope to have a new server up very soon.

**Comment by stefanalund** [comment]
A new version 0.3.95 is now available from a new server, please try running `pod install` again.
