### ISSUE TITLE
Problem with sdp response

### ISSUE THREAD

**Issue by JPNavilo** [EricssonResearch/openwebrtc-ios-sdk#57]
Hi, I've deployed the Native Demo app and am now trying to run video chat tests between my device and a my laptop running firefox. Everything works fine when I use the demo site (http://demo.openwebrtc.org:38080/), but when I attempt to deploy the Ericsson demo on my test webpage (http://motherbase.wearecactus.com:10080/), I get a crash reading [@"sdp"][@"sdp"], there are nothing there (like I saw in the json which comes from the demo site.
If you need more details, the log or anything just tell me...
Thank you all.

**Comment by stefanalund** [comment]
The quick fix is probably to remove one of the `[@"sdp"]` on the iOS side. It may be that what is live on openwebrtc.org is not the latest, hmm...

**Comment by superdump** [comment]
I feel like we should be able to identify what the actual problem is and fix it, or at least make this work for both cases. People seem to always hit this issue...

**Comment by stefanalund** [comment]
Should be fixed now: https://github.com/EricssonResearch/openwebrtc-examples/pull/181. Let us know if you have any remaining problems.
