### ISSUE TITLE
Error installing OpenWebRTC

### ISSUE THREAD

**Issue by minthukyaw99** [EricssonResearch/openwebrtc-ios-sdk#61]
I tried to run pod install and i got the following error:
Failed to connect to static.verkstad.net port 80: Connection refused.

**Comment by superdump** [comment]
From where you are running pod install:

`rm -rf Pods Podfile.lock && pod install`

The Podfile.lock will try to install from an older version which is no longer available at its original location and cocoapods does not allow us to update the address of the file.
