### ISSUE TITLE
Is turn and stun server  necessary when using openwebrtc-ios-sdk ?

### ISSUE THREAD

**Issue by yingzhuo1314** [EricssonResearch/openwebrtc-ios-sdk#70]
hello,
    I'm really a newer in this field. My test native application is running in a LAN network,and our signaling server use openfire server. Is turn and stun server  necessary ? Please give me an answer.

thanks very much.

**Comment by stefanalund** [comment]
STUN is necessary in most cases, and TURN for some cases when you have more advanced network configurations. I would recommend reading this article:

http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
