### ISSUE TITLE
I need to create a video call iOS app with openwebRTC. I can't able to integrate pod file to my existing project .Is there OpenwebRTC SDK with out POD support

### ISSUE THREAD

**Issue by sibineshMc** [EricssonResearch/openwebrtc-ios-sdk#74]
I need an integration support to openwebrtc with out pod file . I can't able to integrate pod file to existing project .Is this possible to I need to create a video call iOS app with openwebRTC. I can't able to integrate pod file to existing project .Is there OpenwebRTC SDK with out POD support

**Comment by sibineshMc** [comment]
I need an integration support to openwebrtc with out pod file . I can't able to integrate pod file to existing project .Is this possible to I need to create a video call iOS app with openwebRTC. I can't able to integrate pod file to existing project .Is there OpenwebRTC SDK with out POD support

**Comment by stefanalund** [comment]
Yes sure. Inside the podspec file you can see the link to the OpenWebRTC.framework file. You can download that and drag it in to your project without using the pod file.

**Comment by stefanalund** [comment]
https://github.com/EricssonResearch/openwebrtc-examples/wiki/Developing-iOS-apps
