### ISSUE TITLE
Error on Pod install

### ISSUE THREAD

**Issue by LucasReyre** [EricssonResearch/openwebrtc-ios-sdk#78]
I'm getting this error when I'm performing a pod Install : 
Installing OpenWebRTC (0.3.95)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/x2/y410j8390dzgc8m98jy_6wfr0000gn/T/d20161007-31888-1rt21ez/file.zip https://pods.cct.ericsson.net/OpenWebRTC_0.3.95.zip --create-dirs --netrc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: pods.cct.ericsson.net

Tried on 2 differents networks and computers.
Anyone has an ideas ?

**Comment by stefanalund** [comment]
We are having some server problems at the moment, so this is to be expected (unfortunately).

**Comment by LucasReyre** [comment]
ok thank's for your reply.

**Comment by LucasReyre** [comment]
When could we expect the server to be up ?

**Comment by Hans92** [comment]
How much time will it take to make server up again?

**Comment by cguzmanceti** [comment]
Hi,

Some alternative server to download this file?

Thank you very much!

**Comment by stefanalund** [comment]
We are working on it...

**Comment by superdump** [comment]
https://pods.cct.ericsson.net/OpenWebRTC_0.3.95.zip is back online. The others in the 0.3.9x series will be soon too though .95 is the newest.

**Comment by cguzmanceti** [comment]
Thanks!! Great news!!
