### ISSUE TITLE
Libraries in podspec

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc-ios-sdk#9]
For some reason the libraries specified in the podspec file(s) are not carried over to the Xcode project:

`s.libraries = "c++", "iconv", "resolve", "z"`

**Comment by stefanalund** [comment]
Correction: only libc++ and libresolv are needed.

**Comment by wzhcxw** [comment]
#import "owr.h"   ,    owr.h   No found,    why ?

**Comment by stefanalund** [comment]
Then the OpenWebRTC pod that contains the framework has not been correctly installed. Do you have it in your Podfile?

If you use the latest OpenWebRTC-SDK pod the other pod should be installed as a dependency. 

How does your Podfile look?

**Comment by wzhcxw** [comment]
This is NativeDemo   podfile:
****************************************************************************************************************
platform :ios, '8.0'

target 'NativeDemo' do
    pod 'InAppSettingsKit', '~> 2.4.4'
    pod 'OpenWebRTC', :path => './openwebrtc-ios-sdk/OpenWebRTC.podspec'
    #pod 'OpenWebRTC', '~> 0.1'
    pod 'OpenWebRTC-SDK', :path => './openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
end

target 'NativeDemoTests' do
    pod 'OpenWebRTC', :path => './openwebrtc-ios-sdk/OpenWebRTC.podspec'
    #pod 'OpenWebRTC', '~> 0.1'
    pod 'OpenWebRTC-SDK', :path => './openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
end
****************************************************************************************************************




This is  openwebrtc-ios-sdk  podfile:
****************************************************************************************************************
platform :ios, '8.0'

target 'NativeDemo' do
    pod 'OpenWebRTC', '~> 0.1'
    pod 'OpenWebRTC-SDK', :path => ‘/../NativeDemo.xcodeproj’
end
****************************************************************************************************************

Is  right?

**Comment by wzhcxw** [comment]
This is Run "pod install " result:
*****************************************************************************************************
localhost:nativedemo johan$ pod install
Analyzing dependencies
Fetching podspec for `OpenWebRTC` from `./openwebrtc-ios-sdk/OpenWebRTC.podspec`
Fetching podspec for `OpenWebRTC-SDK` from `./openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Using OpenWebRTC (0.1.1)
Using OpenWebRTC-SDK (0.1)
Generating Pods project
Integrating client project
localhost:nativedemo johan$

**Comment by stefanalund** [comment]
Now I see. The NativeDemo Podfile does not use the latest version of the SDK pod.

**Comment by wzhcxw** [comment]
Whitch version is  the latest ?

OpenWebRTC version is 0.2?

**Comment by stefanalund** [comment]
0.1.2 see here https://github.com/EricssonResearch/openwebrtc-ios-sdk

(Sorry for the bad support, I'm on my phone :))

**Comment by wzhcxw** [comment]
Me too ,   on iphone

**Comment by wzhcxw** [comment]
#import "owr.h" , owr.h No found,

The latest version..0.1.2


localhost:nativedemo johan$ pod install
Analyzing dependencies
Fetching podspec for `OpenWebRTC` from `./openwebrtc-ios-sdk/OpenWebRTC.podspec`
Fetching podspec for `OpenWebRTC-SDK` from `./openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Installing OpenWebRTC 0.1.2 (was 0.1.1)
Installing OpenWebRTC-SDK 0.1.1 (was 0.1)
Generating Pods project
Integrating client project
localhost:nativedemo johan$

**Comment by stefanalund** [comment]
Hmm...Try removing the "pod OpenWebRTC" from the Podfile, remove the file Podfile.lock, run pod install again and then do a clean build in Xcode.

**Comment by wzhcxw** [comment]
I do it  what you said,   but No found   owr.h  still  exist，help me modify  podfile , Think you .

This is NativeDemo podfile:

platform :ios, '8.0'

target 'NativeDemo' do
pod 'InAppSettingsKit', '~> 2.4.4'
pod 'OpenWebRTC', :path => './openwebrtc-ios-sdk/OpenWebRTC.podspec'
#pod 'OpenWebRTC', '~> 0.1.2'
pod 'OpenWebRTC-SDK', :path => './openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
end

target 'NativeDemoTests' do
pod 'OpenWebRTC', :path => './openwebrtc-ios-sdk/OpenWebRTC.podspec'
#pod 'OpenWebRTC', '~> 0.1.2'
pod 'OpenWebRTC-SDK', :path => './openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec'
end

This is openwebrtc-ios-sdk podfile:

platform :ios, '8.0'

target 'NativeDemo' do
pod 'OpenWebRTC', '~> 0.1.2'
pod 'OpenWebRTC-SDK', :path => ‘/../NativeDemo.xcodeproj’
end

**Comment by wzhcxw** [comment]
I try  run  Mac Demo ,  No found owr.h still exist

**Comment by stefanalund** [comment]
Are you opening the cc workspace file and not xcproject?

**Comment by stefanalund** [comment]
Should be xcworkspace

**Comment by wzhcxw** [comment]
YES,  xcworkspace, But not succeful

**Comment by stefanalund** [comment]
I'll have a look at this on Sunday and get back to you. Sorry for the annoyance.

**Comment by stefanalund** [comment]
@wzhcxw it works for me now. I have cleaned up the Podfile and and after running `pod install` and then `open NativeDemo.xcworkspace` it compiles. I have added some more information here: https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/NativeDemo

Closing this issue, let me know if you still have problems.

**Comment by wzhcxw** [comment]
Think you . It works for me.   so cool.

Now I know Great Firewall of China  Shield some Resource , Need Over the wall  to download something.  

Think you  againe.

**Comment by stefanalund** [comment]
@wzhcxw you are welcome!

**Comment by adrianbg** [comment]
I'm also having this issue. My Podfile is the one in the examples repository:

platform :ios, '8.0'

target 'NativeDemo' do
    pod 'InAppSettingsKit', '~> 2.4.4'
    pod 'OpenWebRTC-SDK',  :git => 'https://github.com/EricssonResearch/openwebrtc-ios-sdk.git'
end

target 'NativeDemoTests' do
    pod 'OpenWebRTC-SDK',  :git => 'https://github.com/EricssonResearch/openwebrtc-ios-sdk.git'
end


I removed Podfile.lock, ran "pod install", then "open NativeDemo.xcworkspace/" and I get this build error:
"owr.h not found".

I'm also unclear on the instructions to add libresolv.dylib and libc++.dylib to the Frameworks folder of my project. Where do I get these files from?

Any idea what's going on?

**Comment by stefanalund** [comment]
Yes and I think I "solved" it last night. There seems to be something in the newer version of CocoaPods that breaks the xcproject file. By downgrading to 0.38.2 and rerunning pod install I got rid of this problem. Make sure to revert the changes to xcproject first.

**Comment by stefanalund** [comment]
@adrianbg is your `pod --version` 0.39.0? You can downgrade by running `sudo gem install cocoapods -v 0.38.2`. Just to be sure I removed my old versions of CocoaPods before installing the new one.

**Comment by adrianbg** [comment]
Sorry for not responding. Yes, downgrading does seem to have helped. I'm
now running into a different error. Thanks!

**Comment by virorum** [comment]
As a quick fix, in the Pods project, open up Header Search Paths in Build Settings and change ${PODS_ROOT}/Headers/Public to be recursive

**Comment by stefanalund** [comment]
@virorum thanks! Any idea how to fix this properly? It's most likely something the the podspec that needs  changing.

**Comment by virorum** [comment]
I think you're right, but I couldn't find any obvious way to patch it up unfortunately :(

**Comment by adrianbg** [comment]
Me neither. glib's configure script generates that header, so someone who
hacks on OpenWebRTC would likely be in a position to get it by adding
x86_64 to a list of architectures somewhere.

**Comment by adrianbg** [comment]
Oops, wrong thread.

**Comment by ohjuju** [comment]
@stefanalund @wzhcxw  hihi, can you send me a install success cocoapod demo? I meet the same problem beacause of the wall but can't download over the wall for my office network. my email address is ouq68@outlook.com,Thx very much. :)

**Comment by stefanalund** [comment]
@ohjuju the file is too big to put in an email unfortunately (~400 MB). Don't you have access to some other NW? Does Dropbox work?

**Comment by ohjuju** [comment]
@stefanalund  yes,it work. Can u share me a link? Thx : )

**Comment by stefanalund** [comment]
Before doing that I want to ensure that you can't access this file: http://static.verkstad.net/OpenWebRTC_0.3.91.zip

**Comment by ohjuju** [comment]
@stefanalund  Thx very much, I think i can download it for the link.   

BTW, can the OpenWebRTC support mutiplies video chat now? haha..
